spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        # 1. Маршрут для пользователей (админка)
        - id: user_service_route
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**

        # 2. Маршрут для заявок (requests)
        - id: request_service_route
          uri: lb://request-service
          predicates:
            - Path=/admin/requests/**,/users/{userId}/requests/**,/users/{userId}/events/{eventId}/requests/**

        # 3. Маршрут для событий, категорий и подборок
        - id: event_service_route
          uri: lb://event-service
          predicates:
            - Path=/admin/events/**,/events/**,/users/{userId}/events/**,/admin/categories/**,/categories/**,/admin/compilations/**,/compilations/**

        # 4. Маршрут для комментариев
        - id: comment_service_route
          uri: lb://comment-service
          predicates:
            - Path=/admin/comments/**,/users/{userId}/comments/**,/users/{userId}/events/{eventId}/comments/**,/events/{eventId}/comments

server:
  port: 8080

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: DEBUG